global:
  stage: dev
  projectName: infrastructure-charts
  source:
    repoURL: "https://github.com/iits-consulting/showcase-otc-infrastructure-charts.git"
    targetRevision: main
    appsBasePath: "stages/$STAGE/infrastructure-charts/apps"
storage-class:
  namespace: default