global:
  stage: dev
  projectName: infrastructure-charts
  source:
    repoURL: "https://github.com/iits-consulting/showcase-otc-infrastructure-charts.git"
    targetRevision: main
    appsBasePath: "stages/$STAGE/infrastructure-charts/apps"
storage-classes:
  namespace: default
cert-manager:
  namespace: cert-manager
kafka:
  namespace: kafka
  helm:
    parameters:
      - name: dns.domain
        value: "admin.$STAGE-fridaytalk.iits.tech"
traefik:
  helm:
    parameters:
      - name: traefik.service.annotations.kubernetes\.io\/elb\.id
        value: "50435e3d-dee2-4294-b6d8-b68c4f554395"
  ignoreDifferences:
    - jsonPointers:
        - /metadata/annotations
      kind: Service
  namespace: routing
elastic-stack:
  namespace: monitoring
  helm:
    parameters:
      - name: dns.domain
        value: "admin.$STAGE-fridaytalk.iits.tech"