traefik:
  globalArguments:
    - "--global.checknewversion"
  logs:
    general:
      format: json
      level: INFO
    access:
      format: json
      enabled: false
  image:
    tag: 2.3.3
  deployment:
    replicas: 1
  service:
    type: LoadBalancer
    spec:
      externalTrafficPolicy: Cluster
  providers:
    kubernetesCRD:
      enabled: true
    kubernetesIngress:
      enabled: true
  ports:
    internalhttps:
      exposedPort: 8444
      port: 8444
      expose: false
      protocol: TCP
      tls:
        enabled: false
domain: "admin.fridaytalk.iits.tech"

