traefik:
  globalArguments:
    - "--global.checknewversion"
  logs:
    general:
      format: json
      level: INFO
    access:
      format: json
      enabled: false
  image:
    tag: 2.3.3
  deployment:
    replicas: 1
  service:
    type: LoadBalancer
    annotations:
      kubernetes.io/elb.id: "SET_BY_STAGEVALUES"
    spec:
      externalTrafficPolicy: Cluster
  providers:
    kubernetesCRD:
      enabled: true
    kubernetesIngress:
      enabled: true
admin:
  url: "admin.REPLACE_ME"
  certificate:
    name: admin-cert
    clusterIssuer: letsencrypt
