kafka:
  replicaCount: 3
  maxMessageBytes: _52428800
  autoCreateTopicsEnable: true
  deleteTopicEnable: false #this has to be disabled to get rid of autoCreateTopicsEnable, which should not be enabled on production. At the moment we cannot delete it, since auto creation happened for some topics
  metrics:
    kafka:
      enabled: true
    jmx:
      enabled: true
  persistence:
    size: 30G
akhq:
  image:
    tag: 0.17.0
  resources:
    requests:
      memory: "400Mi"
      cpu: "1m"
  replicaCount: 1
  configuration: |
    akhq:
      connections:
        kafka:
          properties:
            bootstrap.servers: "kafka:9092"
      server:
        access-log:
          enabled: true
          name: org.akhq.log.access
    micronaut:
      server:
        netty:
          max-initial-line-length: 16384
          max-header-size: 32768
        context-path: "/akhq"
  secrets: ""
  readinessProbe:
    prefix: "/akhq"
dns:
  domain: "SET_BY_STAGE_VALUES"
  hostPrefixRegex: "HostRegexp(`{host:admin.+}`)"
  clusterIssuer: "letsencrypt"
