apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  admin-domain
spec:
  secretName: admin-domain
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: {{ .Values.domain}}
  privateKey:
    algorithm: "RSA"
    size: 4096
  dnsNames:
    - {{.Values.domain}}
