apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  {{ .Release.Name }}-cert
spec:
  secretName: {{ .Release.Name }}-cert
  issuerRef:
    name: {{ .Values.dns.clusterIssuer }}
    kind: ClusterIssuer
  commonName: {{ .Values.dns.domain}}
  privateKey:
    algorithm: "RSA"
    size: 4096
  dnsNames:
    - {{ .Values.dns.domain }}
