apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: {{.Values.dns.hostPrefixRegex}} && PathPrefix(`/akhq`)
      services:
        - kind: Service
          name: {{ .Release.Name }}-akhq
          namespace: {{ .Release.Namespace }}
          passHostHeader: true
          port: 80
  tls:
    secretName: {{ .Release.Name }}-cert